# Generated by Django 5.1.3 on 2024-11-15 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokendata',
            name='price_usd',
        ),
    ]
