# Generated by Django 5.1.3 on 2024-11-15 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_tokendata_price_usd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokendata',
            name='market_cap_usd',
        ),
        migrations.RemoveField(
            model_name='tokendata',
            name='volume_usd',
        ),
    ]
